### ISSUE TITLE
leaderboard

### ISSUE THREAD

**Issue by Nate-Willimack** [nboehlje/se319-midterm-project#7]
Should we create a mongodb to record player(s) scores?

if we do we should create a profile.html.

**Comment by nboehlje** [comment]
yeah I was wondering about that too. Maybe we need a server.

**Comment by Nate-Willimack** [comment]
do you think we need it for this project or should we only have the theorhectical option and then maybe incorporate it for the final project. Because leader board really isn't that big of a deal.

**Comment by nboehlje** [comment]
Yeah I agree, I created a dummy leaderboard just loading a json file using the Fetch api.
