### ISSUE TITLE
todo's

### ISSUE THREAD

**Issue by Nate-Willimack** [nboehlje/se319-midterm-project#9]
I added pretty much all game logic and functions. There are very minor errors that I can't figure out tonight (I've been working on this literally all night). I will be gone for the weekend but will bring my laptop with me so I could potentially code some if need be. I'll list everything that I couldn't get to if you want to do some or all of these that'd be great. 

1. Leaderboards: 
Display the top 10 players with their names and scores.
Allow players to filter by day/week/month or all-time top scores.
Show the player's own rank even if they are not in the top 10.

Doing this I believe would require a server and a database.

2. Add Sound Effects:
Shooting
Enemy being hit/destroyed
Player hit or losing health
Boss appearing/defeated
Bonus drop pickup
Recommendation: Use the HTML5 <audio> element or the Web Audio API to add sound effects for player actions and events in the game. Make sure to preload sounds and limit the number of simultaneous sounds to prevent performance issues.

3. Other player upgrades:
I've already added bonus bullets health drops, but something that upgrades movement speed or temporary invincibility would be cool too.

4. Enemy and Boss AI:
Make the enemies and bosses more dynamic by adding AI behavior that isn't purely random.
Examples:
Enemy spaceships could dodge player bullets or move in specific patterns.
Bosses could have different attack patterns, such as changing the number of bullets fired, their speed, or even special moves at certain health thresholds.
Recommendation: Implement more sophisticated AI for bosses and enemies. For example, after the boss's health drops below a certain percentage, it could change its attack pattern or speed up.

5. Player Lives or Checkpoints:
Instead of instantly ending the game when the player dies, you could add multiple lives or a checkpoint system where the player restarts from a certain point.

Recommendation: Add a life system where the player has multiple lives before the game is over. You can also add checkpoints after certain scores or levels so players can continue from that point when they lose.

6. Visual Effects:
Enhance the game's visual appeal with simple particle effects for explosions or power-ups.

Recommendation: Use particle effects when enemies explode or when the player picks up a bonus drop. You can simulate these effects by spawning small particles (colored divs) that animate and disappear.

7. Mobile Responsiveness:
Make sure your game is playable on mobile devices. Touch controls should replace keyboard inputs for player movement and shooting.

Recommendation: Add touch controls for mobile players, such as a virtual joystick for movement and a button for shooting. You can adjust the game area and controls to fit smaller screens as well.

8.Score Multiplier:
Implement a score multiplier that rewards players for performing certain actions, like destroying enemies in quick succession or avoiding damage for a certain period.
Recommendation: Add a system where players earn a higher score for stringing together enemy kills in quick succession (a combo system). You can increase the multiplier the longer they stay alive without taking damage.

9.Mini-boss Battles:
Along with the main boss at 5000 points, you could introduce mini-bosses at certain intervals. These would be stronger than regular enemies but easier than the main boss.
Recommendation: Add mini-bosses every 1000 or 2000 points to keep the player on their toes and to make the gameplay feel more varied. They could also give bonus loot of some sort.

10. Improve Performance with Object Pooling:
Constantly creating and removing DOM elements (like meteors, spaceships, bullets) can lead to performance bottlenecks, especially as the game progresses. Implementing object pooling could help us optimize the game by reusing these elements instead of constantly creating and destroying them.
Recommendation: Implement a pool for frequently used objects (meteors, bullets, spaceships). When an object is no longer needed, it gets deactivated and returned to the pool rather than destroyed. When you need a new one, you can reuse it from the pool instead of creating a new DOM element each time. Hard to explain so if you have no experience on this don't worry about it. 

All of these are just recommendations, the only thing I really need you to do is make sure all project requirements are met and make the pages more visually appealing; as I've done little to no work on the visuals of the home page leaderboard and team. 

Text me any time if you have any questions!

**Comment by nboehlje** [comment]
@Nate-Willimack 

I just ran through a quick playthrough. I think items 2-10 in your issue can be explored maybe for a final project. Since they are all game-logic related, I don't  think they're essential for the midterm. Your game is already 600+ lines of game logic in JavaScript which is *way* more than I think they're expecting. The level of sophistication of the project is significantly higher than the requirements so I don't think It would make sense to spend the remaining time on adding new features to the game. 

I'm going to work on the leaderboards and getting the project to meet the rubric requirements.
